### ISSUE TITLE
Ошибка при команде refresh

### ISSUE THREAD

**Issue by ig-rudenko** [SemyonYankovskiy/collectioncoin_bot#3]
Traceback (most recent call last):
        File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
          for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
        File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
          return await asyncio.gather(*tasks)
        File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
          response = await handler_obj.handler(*args, **partial_data)
        File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
          return await self.message_handlers.notify(update.message)
        File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
          response = await handler_obj.handler(*args, **partial_data)
        File "/app/limiter.py", line 46, in wrapper
          return await handler(message, *args, *kwargs)
        File "/app/main.py", line 77, in refresh_data
          refresh(message.from_user.id)
        File "/app/site_calc.py", line 85, in refresh
          DataCoin(user.telegram_id, total, user_coin_id).debug()
        File "/app/database.py", line 91, in debug
          db.cursor.execute(
      sqlite3.OperationalError: incomplete input

**Comment by ig-rudenko** [comment]
```python
    def debug(self):
        db = Database()
        db.cursor.execute(f"SELECT COUNT(*) FROM graph_data WHERE tg_id = {self.telegram_id}")
        # Для каждого пользователя в результате запроса

        (count,) = db.cursor.fetchone()
        if count >= 30:
            return

        # кол-во пропущенных значений
        delta: int = 30 - count

        query = ""
        day_increment = date.today()
        for _ in range(delta):
            query += f"({self.telegram_id}, '{day_increment.strftime('%Y.%m.%d')}', {self.totla_sum}, {self.user_coin_id}),"
            day_increment -= timedelta(days=1)

        try:
            db.cursor.execute(
                f"INSERT INTO graph_data (tg_id, datetime, totla_sum, user_coin_id) "
                f"VALUES {query[0:-1]}"
            )
            db.conn.commit()
        except sqlite3.IntegrityError as error:
            print(f"ГРОБ ГРОБ КЛАДБИЩЕ МОГИЛА СМЕРТЬ ГАВНО -> {error}")
```
